#!/bin/bash

SFS_HID_DEV="/sys/bus/hid/devices"
SFS_HID_DRV="/sys/bus/hid/drivers"
SFS_HID_GEN="$SFS_HID_DRV/hid-generic"

# kernels before 3.5.0 use generic-usb, while newer ones have hid-generic
[[ -d "$SFS_HID_DRV/generic-usb" ]] && SFS_HID_GEN="$SFS_HID_DRV/generic-usb"
[[ -d "$SFS_HID_DRV/hid-generic" ]] && SFS_HID_GEN="$SFS_HID_DRV/hid-generic"

rebind()
{
  # assume device is unbound if CONFIG_HID or CONFIG_HID_GENERIC are not enabled
  if [[ -n "$SFS_HID_GEN" ]] ; then
    for dev in $(ls $SFS_HID_GEN | egrep $1) ; do
      echo -n $dev > $SFS_HID_GEN/unbind
    done
  fi
  
  for dev in $(ls $SFS_HID_DEV | egrep $1) ; do
    echo -n $dev > $SFS_HID_DRV/$2/bind
  done
}

rebind 046D:C21C hid-g13
rebind 046D:C222 hid-g15
#rebind 046D:C227 hid-g15v2
rebind 046D:C229 hid-g19
rebind 046D:C22B hid-g110

# TODO: the previous version used to unbind C22D and C22E as well, though it did not bind it to anything
