#!/bin/sh

# run me as root

SFS_HID_DEV="/sys/bus/hid/devices"
SFS_HID_DRV="/sys/bus/hid/drivers"
SFS_HID_GEN="$SFS_HID_DRV/hid-generic"

rebind()
{
  for dev in $(ls $SFS_HID_GEN | egrep $1) ; do
    echo -n $dev > $SFS_HID_GEN/unbind
  done
  
  for dev in $(ls $SFS_HID_DEV | egrep $1) ; do
    echo -n $dev > $SFS_HID_DRV/$2/bind
  done
}

rebind 046D:C21C hid-g13
rebind 046D:C222 hid-g15
#rebind 046D:C227 hid-g15v2
rebind 046D:C229 hid-g19
rebind 046D:C22B hid-g110
